[package]
name = "omnitak-cot"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.36"
prost = "0.13"
prost-types = "0.13"
bytes = "1.7"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"

[build-dependencies]
prost-build = "0.13"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "parse_bench"
harness = false
